name: Build Desktop JAR

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :composeApp:packageUberJarForCurrentOS --no-daemon
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: mani-desktop
          retention-days: 1
          path: |
            composeApp/build/compose/jars/*.jar
