name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest, self-hosted ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        #  run: ./gradlew :server:publishImageToLocalRegistry --no-daemon
        run: ./gradlew :server:buildFatJar --no-daemon

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Login to GitLab
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          context: ./server/
          push: true
          tags: mani-backend:latest
          platforms: linux/arm64, linux/amd64
      - name: Inspect
        run: |
          docker buildx imagetools inspect mani/mani-backend:latest

