name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ macos, self-hosted ]
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 20
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
      #  run: ./gradlew :server:publishImageToLocalRegistry --no-daemon
        run: ./gradlew :server:buildFatJar --no-daemon

      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        with:
          context: ./server/
          push: true
          tags: localhost:5000/mani/mani-backend:latest
          platforms: linux/arm64
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/mani/mani-backend:latest

