name: Deploy

on:
  push:

jobs:
  test:
    runs-on: [macos, self-hosted]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew :server:buildFatJar --no-daemon
