name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ linux, self-hosted ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'corretto'
#          java-version: 21
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#      - name: Build
#        run: ./gradlew :server:publishImage -PBUILD_NUMBER=${{github.run_number}} -PREGISTRY_HOSTNAME=${{vars.REGISTRY_HOSTNAME}} -PREGISTRY_USERNAME=${{secrets.REGISTRY_USERNAME}} -PREGISTRY_PASSWORD=${{secrets.REGISTRY_PASSWORD}} --no-daemon

      - name: 'Portainer Deploy'
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          token: ${{ secrets.PORTAINER_API_KEY }}
          url: ${{ secrets.PORTAINER_URL }}
          name: mani-staging
          standalone: true
          file: /mani-staging/mani-staging/docker-compose.yaml
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_PASSWORD }}
