name: Deploy

on:
  push:

jobs:
  build:
    runs-on: [ macos, self-hosted ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew :server:buildFatJar --no-daemon

  docker:
    needs:
      build
    runs-on: [ macos, self-hosted ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


