name: Test

on:
  push:
  pull_request:
    branches: main
  
jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 20
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test shared
      run: ./gradlew :shared:jvmTest :server:test --no-daemon
