name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew --build-cache --gradle-user-home cache/ :shared:jvmTest :server:test :composeApp:desktopTest --no-daemon